### ISSUE TITLE
Should it update Location in Background on Android?

### ISSUE THREAD

**Issue by csaggo** [farfromrefug/nativescript-gps#18]
it says:
This is a plugin to receive gps location updates regardless of the app state

so i am calling the watchLocation method like this on android:
`gps
                .watchLocation(
                  newLocation,
                  e => {
                    console.log(e);
                  },
                  {
                    provider: "gps",
                    minimumUpdateTime: 1000,
                    skipPermissionCheck: true
                  }
                )
                .then(watchId => {
                  watchIds.push(watchId);
                });`
                
                
 But as soon as i switch to another app (not closing the app but having it in Background) it stops getting locations. It only continues to call newLocation when i put it in foreground again.
 
 Is that a missunderstanding? what does regardless of app-state mean?
 
 thank you

**Comment by farfromrefug** [comment]
@csaggo yes it will receive regardless of the state. But you need to handle permissions and specific platforms restrictions. 
You need to look how it works on each platform, mainly Android which has deep restrictions (permissions, foreground services)...

**Comment by csaggo** [comment]
Allright i see, i thought the service aspect of android was something the plugin might be handling, understood, this has to be done outside.
thanks for clarification

**Comment by farfromrefug** [comment]
@csaggo it could be but it would not be easy to configure, make cross platform ... so thought it would be better to let users do it.
Here is how i do it https://github.com/farfromrefug/alpimaps/blob/master/app/services/BgService.android.ts. We could make it a sample demo here if someone wanted to make a PR for it

**Comment by csaggo** [comment]
@farfromrefug hi we had a break in the project but we are moving on. sorry to bother you again but i am stuck :-(

thanks so much for the example! i copied the BgService (with all the different files) from your project and only removed some parts i wont need (localisation for example)

According to your app i instantiate the /services/BgService in app.js (i am doing vanilla js, but have added typescript to not have to rewrite everything)

now when the app launches i get this error:

An uncaught Exception occurred on "main" thread.
Unable to create service at.herzlauf.herzlauf.BgService: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'at/herzlauf/herzlauf/BgService'

StackTrace:
java.lang.RuntimeException: Unable to create service at.herzlauf.herzlauf.BgService: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'at/herzlauf/herzlauf/BgService'
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'at/herzlauf/herzlauf/BgService'
	at com.tns.Runtime.createJSInstanceNative(Native Method)
	at com.tns.Runtime.createJSInstance(Runtime.java:835)
	at com.tns.Runtime.initInstance(Runtime.java:808)
	at at.herzlauf.herzlauf.BgService.onCreate(BgService.java:29)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
	... 8 more



i have renamed the package everywhere and added all the relevant entries to the AndroidManifest.xml
but it seems i am missing something.

in case you dont have an idea on top of your head maybe we can book you for an hour to do a skype call with me (paid obviously) as after the break we are now overdue and the customer is in our neck :-/

**Comment by sivo1981** [comment]
I have the same error after upgrading from NS 7 to NS8 and Android SDK 30 to 31.

  System.err: java.lang.RuntimeException: Unable to create service si.ribiskekarte.ecuvaj.location.ForegroundService: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'si  /ribiskekarte/ecuvaj/location/ForegroundService'
  System.err:   at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
  System.err:   at android.app.ActivityThread.access$1700(ActivityThread.java:247)
  System.err:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:106)
  System.err:   at android.os.Looper.loopOnce(Looper.java:201)
  System.err:   at android.os.Looper.loop(Looper.java:288)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:7839)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
  System.err: Caused by: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'si/ribiskekarte/ecuvaj/location/ForegroundService'
  System.err:   at com.tns.Runtime.createJSInstanceNative(Native Method)
  System.err:   at com.tns.Runtime.createJSInstance(Runtime.java:835)
  System.err:   at com.tns.Runtime.initInstance(Runtime.java:808)
  System.err:   at si.ribiskekarte.ecuvaj.location.ForegroundService.onCreate(ForegroundService.java:30)
  System.err:   at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
  System.err:   ... 9 more
